name: Node.js environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome
        run: echo Hello, Github Actions!
      - name: Configuration
        run: echo Setup your Node project
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
      - run: npm install
      - run: npm test