name: 'Test Report'

on:
  workflow_run:
    workflows: ['Node.js environment']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Install Node'
        uses: actions/setup-node@v2.4.1
      - name: Install dependencies
        run: npm install 
      - name: Install chai
        run: npm install -g chai
      - name: Install mocha
        run: npm install -g mocha
      - name: "Run Test"
        run: npm run test